### ISSUE TITLE
App crashes if not focused when notification is recieved

### ISSUE THREAD

**Issue by jlugner** [oney/TestGcm#1]
The app works fine while the view is rendered, but if I recieve a notification while at my home screen, the app simply crashes. Any suggestions? I get the same behaviour in my own app when I use this library.

**Comment by oney** [comment]
What is the data when sending the GCM notification?
As the [doc](https://github.com/oney/react-native-gcm-android) said, you should send the notification like below

``` json
{
  "data": {
    "largeIcon": "ic_launcher",
    "contentTitle": "Awesome app",
    "message": "Hi, how are you?",
    "ticker": "hi..."
  }, 
  "collapse_key": "updated_score"
}
```

**Comment by jlugner** [comment]
Completely missed, working as expected now. Closing issue, thanks for quick reply!
