### ISSUE TITLE
A problem occurred configuring project ':RNGcmAndroid'

### ISSUE THREAD

**Issue by ayush29feb** [oney/TestGcm#4]
Hey I am trying to run the program but I keep receiving this error.

studentusersMBP:TestGcm studentuser$ react-native run-android --stacktrace
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':RNGcmAndroid'.
  
  > Could not resolve all dependencies for configuration ':RNGcmAndroid:_debugCompile'.
  > Could not find com.google.android.gms:play-services-gcm:8.1.0.
  >  Searched in the following locations:
  >      file:/Users/studentuser/.m2/repository/com/google/android/gms/play-services-gcm/8.1.0/play-services-gcm-8.1.0.pom
  >      file:/Users/studentuser/.m2/repository/com/google/android/gms/play-services-gcm/8.1.0/play-services-gcm-8.1.0.jar
  >      https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/8.1.0/play-services-gcm-8.1.0.pom
  >      https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/8.1.0/play-services-gcm-8.1.0.jar
  >      file:/usr/local/opt/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/8.1.0/play-services-gcm-8.1.0.pom
  >      file:/usr/local/opt/android-sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/8.1.0/play-services-gcm-8.1.0.jar
  >  Required by:
  >      TestGcm:RNGcmAndroid:unspecified
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.434 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by nbastoWM** [comment]
You have to install google-play-services and repository on Android SDK.

**Comment by ayush29feb** [comment]
Yeah, I realized that, thanks a lot for the response.

**Comment by nachikettrivedi** [comment]
@nbastoWM I have google play services and google repository already installed. I'm still facing the same error of: RNGcmAndroid' A problem occurred configuring project ':RNGcmAndroid'. Please guide.

**Comment by ayush9** [comment]
@oney @nbastoWM  I have google play services and google repository already installed. I'm still facing the same error of: RNGcmAndroid' A problem occurred configuring project ':RNGcmAndroid'. Please guide.

**Comment by xphaul** [comment]
@ayus did you managed to fix this issue?

**Comment by xphaul** [comment]
@ayush9 did you managed to have a workaround about this issue?
